root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
args_bin = []
bin = "./tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ./"
delay = 0

exclude_dir = ["assets", "tmp", "vendor", "testdata", "uploads", ".idea", ".git", ".vscode"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = false

include_dir = ["."]
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "sql", "jpeg", "jpg"]
include_file = []
kill_delay = 0
log = "build-errors.log"
rerun = false
