.PHONY: all run_dev_web run_dev_mobile run_unit clean upgrade lint format build_dev_mobile help

all: lint format run_dev_mobile

# Adding a help file: https://gist.github.com/prwhite/8168133#gistcomment-1313022
help: ## This help dialog.
	@IFS=$$'\n' ; \
	help_lines=(`fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//'`); \
	for help_line in $${help_lines[@]}; do \
		IFS=$$'#' ; \
		help_split=($$help_line) ; \
		help_command=`echo $${help_split[0]} | sed -e 's/^ *//' -e 's/ *$$//'` ; \
		help_info=`echo $${help_split[2]} | sed -e 's/^ *//' -e 's/ *$$//'` ; \
		printf "%-30s %s\n" $$help_command $$help_info ; \
	done

upgrade: clean ## Upgrades dependencies
	@echo "Upgrading dependencies..."
	@flutter pub upgrade

commit: format lint run_unit
	@echo "Committing..."
	git add .
	git commit

run_switch_app: ## Runs the web application in dev
	@echo "Running the app switch_app"
	@flutter run -t lib/main.dart --dart-define=flavor=switch_app --flavor switch_app

run_dev_mobile: ## Runs the mobile application in dev
	@echo "Running the app"
	@flutter run --flavor dev
build-runner:
	flutter packages pub run build_runner build --delete-conflicting-outputs
run: ## Runs the Flutter app 
	@echo "Running the Flutter app..."
	@flutter run

