name: intern
description: intern app

version: 2.4.7+29

environment:
  sdk: '>=2.17.0 <3.0.0'

scripts: # derry


  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  analyze: flutter analyze --no-pub
  format: flutter format lib/**
  build_android_release: flutter build appbundle -t lib/main.dart
  build_ios_release: flutter build ipa -t lib/main.dart
  build_apk: flutter build apk -t lib/main.dart --split-per-abi build --dart-define=flavor=mathaq --flavor mathaq
  build_web: flutter build web
  build_firebase_deploy: firebase deploy
  build_firebase_deploy_preview_channel: firebase hosting:channel:deploy test
  build_firebase_configure: flutterfire configure
  #flutter gen-l10n
  #uninstall: adb uninstall com.sadeemtech.intern.orion



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  stacked: ^3.4.1+1
  file_picker:
  shared_preferences: ^2.3.2
  built_value: ^8.0.6
  pedantic: ^1.11.0
  get_it: ^7.7.0
  dio: ^4.0.0
  flutter_svg: ^1.0.3
  cached_network_image: ^3.3.0
  pin_code_fields: ^8.0.1
  infinite_scroll_pagination: ^4.0.0
  url_launcher: ^6.0.12
  auto_route: ^7.8.4
  font_awesome_flutter: ^10.1.0
  intl_phone_number_input: ^0.7.1
  universal_platform: ^1.0.0-nullsafety
  timeago: ^3.3.0
  introduction_screen: ^3.1.14
  package_info_plus:
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^10.0.1

  #  fl_chart: ^0.40.0
  top_snackbar_flutter: ^3.1.0
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  analyzer: ^6.7.0
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  built_value_generator: ^8.0.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.1.7
  build_runner_core: ^7.2.3
  #  meta: ^1.7.0
  logger: ^1.0.0
  cookie_jar: ^3.0.1
  dependency_validator: ^3.0.0

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  #  android: "native_splash"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  #  image_path_android: "assets/images/intern/native_splash.png"
  image_path_android: "assets/images/intern/png_logo.png"
  image_path_ios: "assets/images/intern/png_logo.png"
  web:
    generate: true
    image_path: "assets/images/intern/png_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/internship/


  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: SadeemIcon
      fonts:
        - asset: assets/fonts/SadeemIcon.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/native_splash.png
  color_dark: "#ffffff"
  image_dark: assets/images/native_splash.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/native_splash.png

    # Splash screen background color.
    color: "#ffffff"

    # App icon background color.
    icon_background_color: "#eeeeee"


flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  main_locale: ar
  class_name: AppLocalizations # Optional. Sets the name for the generated localization class. Default: S


